title: Trading Pal
description: A trading platform for monitoring and managing financial assets
baseurl: "/Trading_Pal-main"
url: "https://united-visions.github.io"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme settings
minima:
  skin: dark

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
