title: Trading Pal
description: An advanced AI-powered trading platform with multi-broker integration and comprehensive market analysis capabilities
baseurl: "/Trading_Pal-main"
url: "https://united-visions.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Theme settings
minima:
  skin: dark
  social_links:
    github: United-Visions/Trading_Pal-main

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path/

# Default settings
defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Navigation
header_pages:
  - index.html
  - data_server.html
  - charts_display.html
  - backtesting.html

# Sass settings
sass:
  style: compressed
  sass_dir: _sass

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
