title: Trading Pal
description: An advanced AI-powered trading platform with multi-broker integration and comprehensive market analysis capabilities
baseurl: ""
url: "https://united-visions.github.io/Trading_Pal-main"
repository: United-Visions/Trading_Pal-main

# Theme settings
remote_theme: aksakalli/jekyll-doc-theme@gh-pages
bootwatch: slate

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Collections
collections:
  docs:
    output: true
    permalink: /docs/:name/

# Default settings
defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "docs"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Navigation
header_pages:
  - index.html
  - data_server.html
  - charts_display.html
  - backtesting.html

# Sass settings
sass:
  style: compressed
  sass_dir: _sass

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
